//
//  AddStreamView2ViewController.h
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "EasyTracker.h"
#import "TPKeyboardAvoidingTableView.h"
#import "checkerDataManager.h"

@interface AddStreamView2ViewController : TrackedUIViewController <UITextFieldDelegate>{
    
    UITextField *textField1;
    UITextField *textField2;
    UITableViewCell *tableViewCell3;
    UITableViewCell *tableViewCell4;
    UITableViewCell *tableViewCell5;
    
    TPKeyboardAvoidingTableView *tableView1;
    
    checkerDataManager *_data;
  
}

@property (nonatomic, retain) NSMutableArray *tableView1Data;

@end