//
//  HomeViewController.h
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import "EasyTracker.h"
#import "checkerDataManager.h"

@interface HomeViewController : TrackedUIViewController {
    UITableView *_tableView1;
    checkerDataManager *_data;
}

@property (nonatomic, retain) NSMutableArray *tableView1Data;
@property (nonatomic, retain) UITableView *tableView1;

@end