//
//  SetIntervalViewController.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "SetIntervalViewController.h"

@implementation SetIntervalViewController
@synthesize picker1Data;


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return UIInterfaceOrientationIsPortrait(toInterfaceOrientation);
}

- (void)viewDidLoad {
  [super viewDidLoad];
  
  // ----------------------------;
  // View Controller Root View;
  // ----------------------------;
  
  self.view.backgroundColor = [UIColor colorWithRed:0.82 green:0.82 blue:0.82 alpha:1.0];
  UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 460)];
  contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  
  // ----------------------------;
  // UIPickerView -> picker1;
  // ----------------------------;
  
  UIPickerView *picker1 = [[UIPickerView alloc] initWithFrame:CGRectMake(0, 244, 320, 216)];
  picker1.dataSource = (id<UIPickerViewDataSource>)self;
  picker1.delegate = (id<UIPickerViewDelegate>)self;
  picker1.tag = 1;
  self.picker1Data = [NSMutableArray array];
  [contentView addSubview:picker1];
  picker1.alpha = 1.0;
  picker1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  
  
  // ----------------------------;
  // Picker View Column -> pickerViewColumn1;
  // ----------------------------;
  
  NSMutableDictionary *pickerViewColumn1 = [NSMutableDictionary dictionary];
  [pickerViewColumn1 setObject:[NSNumber numberWithFloat:44] forKey:@"rowHeight"];
  [pickerViewColumn1 setObject:[UIColor colorWithRed:0.0 green:0.0 blue:0.5 alpha:1.0] forKey:@"textColor"];
  [pickerViewColumn1 setObject:[NSNumber numberWithInteger:UITextAlignmentLeft] forKey:@"textAlignment"];
  [pickerViewColumn1 setObject:[NSNumber numberWithInteger:UIViewContentModeCenter] forKey:@"contentMode"];
  [pickerViewColumn1 setObject:[NSNumber numberWithFloat:120] forKey:@"componentWidth"];
  [pickerViewColumn1 setObject:[UIFont fontWithName:@"Helvetica-Bold" size:20.0] forKey:@"font"];
  NSMutableArray *pickerViewColumn1Rows = [NSMutableArray array];
  [pickerViewColumn1Rows addObject:@"5 min"];
  [pickerViewColumn1Rows addObject:@"15 min"];
  [pickerViewColumn1Rows addObject:@"30 min"];
  [pickerViewColumn1Rows addObject:@"60 min"];
  [pickerViewColumn1Rows addObject:@"2 hours"];
  [pickerViewColumn1Rows addObject:@"4 hours"];
  [pickerViewColumn1Rows addObject:@"8 hours"];
  [pickerViewColumn1Rows addObject:@"12 hours"];
  [pickerViewColumn1Rows addObject:@"24 hours"];
  [pickerViewColumn1 setObject:pickerViewColumn1Rows forKey:@"rows"];
  [self.picker1Data addObject:pickerViewColumn1];
  
  // ----------------------------;
  // UILabel -> label1;
  // ----------------------------;
  
  UILabel *label1 = [[UILabel alloc] initWithFrame:CGRectMake(20, 57, 284, 80)];
  [contentView addSubview:label1];
  label1.alpha = 1.0;
  label1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  label1.text = @"Set monitoring interval";
  label1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
  label1.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
  label1.textAlignment = UITextAlignmentCenter;
  label1.shadowOffset = CGSizeMake(0, -1);
  label1.font = [UIFont fontWithName:@"Helvetica" size:25.0];
  
  
  // ----------------------------;
  // UINavigationBar -> navigationBar1;
  // ----------------------------;
  
  UINavigationBar *navigationBar1 = [[UINavigationBar alloc] initWithFrame:CGRectMake(0, 0, 320, 44)];
  navigationBar1.delegate = (id<UINavigationBarDelegate>)self;
  UINavigationItem *navigationBar1BackItem = [[UINavigationItem alloc] initWithTitle:nil];
  UINavigationItem *navigationBar1TopItem = [[UINavigationItem alloc] initWithTitle:nil];
  NSArray *navigationBar1Items = [NSArray arrayWithObjects:navigationBar1BackItem, navigationBar1TopItem, nil];
  [navigationBar1 setItems:navigationBar1Items animated:NO];
  [contentView addSubview:navigationBar1];
  navigationBar1.alpha = 1.0;
  navigationBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
  navigationBar1.barStyle = UIBarStyleDefault;
  navigationBar1.tintColor = [UIColor colorWithRed:0.07 green:0.57 blue:1.0 alpha:1.0];
  navigationBar1.topItem.title = @"Set interval";
  [navigationBar1 setTitleVerticalPositionAdjustment:0.0 forBarMetrics:UIBarMetricsDefault];
  
  // ----------------------------;
  // Navigation Bar Lef Button -> barButton1;
  // ----------------------------;
  
  UIBarButtonItem *barButton1 = [[UIBarButtonItem alloc] initWithTitle:@"Back" style:UIBarButtonItemStyleBordered target:nil action:nil];
  barButton1.target = self;
  barButton1.action = @selector(didTap_barButton1:forEvent:);
  
  navigationBar1.topItem.hidesBackButton = NO;
  navigationBar1.backItem.backBarButtonItem = barButton1;
  
  
  // ----------------------------;
  // UISegmentedControl -> segmentedControl1;
  // ----------------------------;
  
  UISegmentedControl *segmentedControl1 = [[UISegmentedControl alloc] initWithFrame:CGRectMake(85, 291, 150, 44)];
  [contentView addSubview:segmentedControl1];
  segmentedControl1.alpha = 1.0;
  segmentedControl1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
  segmentedControl1.enabled = YES;
  segmentedControl1.segmentedControlStyle = UISegmentedControlStylePlain;
  segmentedControl1.selectedSegmentIndex = 1;
  segmentedControl1.tintColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.5 alpha:1.0];
  [segmentedControl1 setSelectedSegmentIndex:0];
  
  
  contentView.frame = self.view.bounds;
  [self.view addSubview:contentView];

}

- (void)viewDidUnload {
  self.picker1Data = nil;
  [super viewDidUnload];
}


- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault animated:animated];
}

// ----------------
// Picker View
// ----------------

- (NSInteger)numberOfComponentsInPickerView:(UIPickerView *)pickerView {
  if (pickerView.tag == 1) {;
    return self.picker1Data.count;
  };
  
  return 0;
}

- (NSInteger)pickerView:(UIPickerView *)pickerView numberOfRowsInComponent:(NSInteger)component {
  if (pickerView.tag == 1) {;
    NSDictionary *componentData = [self.picker1Data objectAtIndex:component];
    return [[componentData objectForKey:@"rows"] count];
  };
  
  return 0;
}
- (CGFloat)pickerView:(UIPickerView *)pickerView rowHeightForComponent:(NSInteger)component {
  if (pickerView.tag == 1) {;
    NSDictionary *componentData = [self.picker1Data objectAtIndex:component];
    return [[componentData objectForKey:@"rowHeight"] floatValue];
  };
  
  return 0;
}

- (CGFloat)pickerView:(UIPickerView *)pickerView widthForComponent:(NSInteger)component {
    if (pickerView.tag == 1) {;
      NSDictionary *componentData = [self.picker1Data objectAtIndex:component];
      return [[componentData objectForKey:@"componentWidth"] floatValue];
    };
    
    return 0;
}
- (UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(UIView *)view {
  if (pickerView.tag == 1) {;
    NSDictionary *componentData = [self.picker1Data objectAtIndex:component];
    CGFloat height = [[componentData objectForKey:@"rowHeight"] floatValue];
    CGFloat width = [[componentData objectForKey:@"componentWidth"] floatValue];
    NSArray *rows = [componentData objectForKey:@"rows"];
    id item = [rows objectAtIndex:row];
      if ([item isKindOfClass:[NSString class]]) {;
        UIColor *textColor = [componentData objectForKey:@"textColor"];
        UIFont *font = [componentData objectForKey:@"font"];
        NSNumber *textAlignment = [componentData objectForKey:@"textAlignment"];
        UILabel *label = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, width, height)];
        label.backgroundColor = [UIColor clearColor];
        label.textColor = textColor;
        label.font = font;
        label.text = item;
        label.textAlignment = textAlignment.integerValue;
        return label;
      };
      if ([item isKindOfClass:[UIImage class]]) {;
        NSNumber *contentMode = [componentData objectForKey:@"contentMode"];
        UIImageView *imageView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, width, height)] ;
        imageView.image = item;
        imageView.backgroundColor = [UIColor clearColor];
        imageView.contentMode = contentMode.integerValue;
        imageView.clipsToBounds = YES;
        return imageView;
      };
  };
  
  return nil;
}


// ----------------
// Navigation Bar
// ----------------

- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
  [self didTap_barButton1:nil forEvent:nil];
  return NO;
}

// ----------------
// Action
// ----------------

- (void)didTap_barButton1:(id)sender forEvent:(UIEvent *)event {
  [self.navigationController popViewControllerAnimated:YES];
}




@end