//
//  SettingsViewController.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "SettingsViewController.h"
#import "HistoryIntervalViewController.h"

@implementation SettingsViewController
@synthesize tableView1Data;


- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return UIInterfaceOrientationIsPortrait(toInterfaceOrientation);
}

- (void)viewDidLoad {
    [super viewDidLoad];
    
    // ----------------------------;
    // View Controller Root View;
    // ----------------------------;
    
    self.view.backgroundColor = [UIColor colorWithRed:0.82 green:0.82 blue:0.82 alpha:1.0];
    UIView *contentView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 460)];
    contentView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    
    // ----------------------------;
    // UINavigationBar -> navigationBar1;
    // ----------------------------;
    
    UINavigationBar *navigationBar1 = [[UINavigationBar alloc] initWithFrame:CGRectMake(0, 0, 320, 44)];
    navigationBar1.delegate = (id<UINavigationBarDelegate>)self;
    UINavigationItem *navigationBar1BackItem = [[UINavigationItem alloc] initWithTitle:nil] ;
    UINavigationItem *navigationBar1TopItem = [[UINavigationItem alloc] initWithTitle:nil] ;
    NSArray *navigationBar1Items = [NSArray arrayWithObjects:navigationBar1BackItem, navigationBar1TopItem, nil];
    [navigationBar1 setItems:navigationBar1Items animated:NO];
    [contentView addSubview:navigationBar1];
    navigationBar1.alpha = 1.0;
    navigationBar1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
    navigationBar1.barStyle = UIBarStyleDefault;
    navigationBar1.tintColor = [UIColor colorWithRed:0.07 green:0.57 blue:1.0 alpha:1.0];
    navigationBar1.topItem.title = @"Settings";
    [navigationBar1 setTitleVerticalPositionAdjustment:0.0 forBarMetrics:UIBarMetricsDefault];
    
    // ----------------------------;
    // Navigation Bar Lef Button -> barButton1;
    // ----------------------------;
    
    UIBarButtonItem *barButton1 = [[UIBarButtonItem alloc] initWithTitle:@"Back" style:UIBarButtonItemStyleBordered target:nil action:nil];
    barButton1.target = self;
    barButton1.action = @selector(didTap_barButton1:forEvent:);
    
    navigationBar1.topItem.hidesBackButton = NO;
    navigationBar1.backItem.backBarButtonItem = barButton1;
    
    
    // ----------------------------;
    // UITableView -> tableView1;
    // ----------------------------;
    
    UITableView *tableView1 = [[UITableView alloc] initWithFrame:CGRectMake(0, 42, 320, 416) style:UITableViewStyleGrouped];
    tableView1.tag = 1;
    tableView1.delegate = (id<UITableViewDelegate>)self;
    tableView1.dataSource = (id<UITableViewDataSource>)self;
    self.tableView1Data = [NSMutableArray array];
    [contentView addSubview:tableView1];
    tableView1.alpha = 1.0;
    tableView1.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    tableView1.separatorStyle = UITableViewCellSeparatorStyleSingleLineEtched;
    tableView1.separatorColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.18];
    tableView1.backgroundColor = [UIColor colorWithRed:0.82 green:0.82 blue:0.82 alpha:1.0];
    
    
    // ----------------------------;
    // Table View Section -> tableViewSection1;
    // ----------------------------;
    
    NSMutableDictionary *tableViewSection1Data = [NSMutableDictionary dictionary];
    [tableViewSection1Data setObject:@"" forKey:@"headerText"];
    [tableViewSection1Data setObject:@"" forKey:@"footerText"];
    [tableViewSection1Data setObject:[NSNumber numberWithBool:YES] forKey:@"customFooterView"];
    [tableViewSection1Data setObject:[NSMutableArray array] forKey:@"cells"];
    [self.tableView1Data addObject:tableViewSection1Data];
    
    // ----------------------------;
    // Custom Footer -> tableViewFooterView1;
    // ----------------------------;
    
    UIView *tableViewFooterView1 = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 60)] ;
    [tableViewSection1Data setObject:tableViewFooterView1 forKey:@"footerView"];
    [tableViewSection1Data setObject:[NSNumber numberWithFloat:60] forKey:@"customFooterViewHeight"];
    
    // ----------------------------;
    // Custom Cell -> tableViewCell1;
    // ----------------------------;
    
    NSMutableDictionary *tableViewCell1Data = [NSMutableDictionary dictionary];
    UIView *tableViewCell1CustomView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 300, 49)] ;
    tableViewCell1CustomView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    UITableViewCell *tableViewCell1 = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:nil] ;
    tableViewCell1.accessoryType = UITableViewCellAccessoryNone;
    [tableViewCell1Data setObject:tableViewCell1 forKey:@"cell"];
    [tableViewCell1Data setObject:[NSNumber numberWithInteger:UITableViewCellEditingStyleDelete] forKey:@"editingStyle"];
    [tableViewCell1Data setObject:[NSNumber numberWithFloat:50.0] forKey:@"height"];
    [tableViewCell1Data setObject:[NSNumber numberWithBool:YES] forKey:@"showReorderControl"];
    [[tableViewSection1Data objectForKey:@"cells"] addObject:tableViewCell1Data];
    
    // ----------------------------;
    // UISwitch -> switch1;
    // ----------------------------;
    
    UISwitch *switch1 = [[UISwitch alloc] init];
    [switch1 sizeToFit];
    CGRect switch1Rect = switch1.frame;
    switch1Rect.origin.x = 205;
    switch1Rect.origin.y =  10;
    switch1.frame = switch1Rect;
    [tableViewCell1CustomView addSubview:switch1];
    switch1.alpha = 1.0;
    switch1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
    switch1.enabled = YES;
    switch1.onTintColor = [UIColor colorWithRed:0.0 green:0.5 blue:0.92 alpha:1.0];
    
    
    // ----------------------------;
    // UILabel -> label1;
    // ----------------------------;
    
    UILabel *label1 = [[UILabel alloc] initWithFrame:CGRectMake(5, 10, 100, 30)];
    [tableViewCell1CustomView addSubview:label1];
    label1.alpha = 1.0;
    label1.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
    label1.text = @"Only Wifi";
    label1.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
    label1.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
    label1.shadowColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
    label1.textAlignment = UITextAlignmentLeft;
    label1.shadowOffset = CGSizeMake(0, -1);
    label1.font = [UIFont fontWithName:@"Helvetica-Bold" size:17.0];
    
    tableViewCell1CustomView.frame = tableViewCell1.contentView.bounds;
    [tableViewCell1.contentView addSubview:tableViewCell1CustomView];
    
    // ----------------------------;
    // Cell -> tableViewCell2;
    // ----------------------------;
    
    NSMutableDictionary *tableViewCell2Data = [NSMutableDictionary dictionary];
    UITableViewCell *tableViewCell2 = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleValue1 reuseIdentifier:nil];
    tableViewCell2.textLabel.text = @"History";
    tableViewCell2.detailTextLabel.text = @"1 week";
    tableViewCell2.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    [tableViewCell2Data setObject:tableViewCell2 forKey:@"cell"];
    [tableViewCell2Data setObject:[NSNumber numberWithInteger:UITableViewCellEditingStyleDelete] forKey:@"editingStyle"];
    [tableViewCell2Data setObject:[NSNumber numberWithInteger:0] forKey:@"indentationLevel"];
    [tableViewCell2Data setObject:[NSNumber numberWithFloat:50.0] forKey:@"height"];
    [tableViewCell2Data setObject:[NSNumber numberWithBool:YES] forKey:@"showReorderControl"];
    [[tableViewSection1Data objectForKey:@"cells"] addObject:tableViewCell2Data];
    [tableViewCell2Data setObject:@"didTap_tableViewCell2:" forKey:@"actionSelector"];
    
    // ----------------------------;
    // Custom Cell -> tableViewCell3;
    // ----------------------------;
    
    NSMutableDictionary *tableViewCell3Data = [NSMutableDictionary dictionary];
    UIView *tableViewCell3CustomView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 300, 49)];
    tableViewCell3CustomView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    UITableViewCell *tableViewCell3 = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:nil];
    tableViewCell3.accessoryType = UITableViewCellAccessoryNone;
    [tableViewCell3Data setObject:tableViewCell3 forKey:@"cell"];
    [tableViewCell3Data setObject:[NSNumber numberWithInteger:UITableViewCellEditingStyleDelete] forKey:@"editingStyle"];
    [tableViewCell3Data setObject:[NSNumber numberWithFloat:50.0] forKey:@"height"];
    [tableViewCell3Data setObject:[NSNumber numberWithBool:YES] forKey:@"showReorderControl"];
    [[tableViewSection1Data objectForKey:@"cells"] addObject:tableViewCell3Data];
    
    // ----------------------------;
    // UILabel -> label2;
    // ----------------------------;
    
    UILabel *label2 = [[UILabel alloc] initWithFrame:CGRectMake(10, 0, 158, 49)];
    [tableViewCell3CustomView addSubview:label2];
    label2.alpha = 1.0;
    label2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
    label2.text = @"Push notification";
    label2.textColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:1.0];
    label2.backgroundColor = [UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.0];
    label2.textAlignment = UITextAlignmentLeft;
    label2.shadowOffset = CGSizeMake(0, -1);
    label2.font = [UIFont fontWithName:@"Helvetica-Bold" size:17.0];
    
    // ----------------------------;
    // UISwitch -> switch2;
    // ----------------------------;
    
    UISwitch *switch2 = [[UISwitch alloc] init];
    [switch2 sizeToFit];
    CGRect switch2Rect = switch2.frame;
    switch2Rect.origin.x = 205;
    switch2Rect.origin.y =  10;
    switch2.frame = switch2Rect;
    [tableViewCell3CustomView addSubview:switch2];
    switch2.alpha = 1.0;
    switch2.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
    switch2.on = YES;
    switch2.enabled = YES;
    switch2.onTintColor = [UIColor colorWithRed:0.0 green:0.5 blue:0.92 alpha:1.0];
    
    tableViewCell3CustomView.frame = tableViewCell3.contentView.bounds;
    [tableViewCell3.contentView addSubview:tableViewCell3CustomView];
    
    
    contentView.frame = self.view.bounds;
    [self.view addSubview:contentView];
    
}

- (void)viewDidUnload {
    self.tableView1Data = nil;
    [super viewDidUnload];
}


- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];
    [[UIApplication sharedApplication] setStatusBarStyle:UIStatusBarStyleDefault animated:animated];
}

// ----------------
// Table View
// ----------------

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    if (tableView.tag == 1) {;
        return self.tableView1Data.count;
    };
    
    return 0;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:section];
        return [[sectionData objectForKey:@"cells"] count];
    };
    
    return 0;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:indexPath.section];
        NSDictionary *cellData =  [[sectionData objectForKey:@"cells"] objectAtIndex:indexPath.row];
        return [cellData objectForKey:@"cell"];
    };
    
    return [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:nil];
}

- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:section];
        return [sectionData objectForKey:@"headerText"];
    };
    
    return nil;
}

- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:section];
        return [sectionData objectForKey:@"footerText"];
    };
    
    return nil;
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:indexPath.section];
        NSDictionary *cellData =  [[sectionData objectForKey:@"cells"] objectAtIndex:indexPath.row];
        return [[cellData objectForKey:@"height"] floatValue];
    };
    
    return tableView.rowHeight;
}

- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:section];
        if ([[sectionData objectForKey:@"customHeaderView"] boolValue]) {;
            return [sectionData objectForKey:@"headerView"];
        } else {;
            return nil;
        };
    };
    
    return nil;
}

- (UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:section];
        if ([[sectionData objectForKey:@"customFooterView"] boolValue]) {;
            return [sectionData objectForKey:@"footerView"];
        } else {;
            return nil;
        };
    };
    
    return nil;
}

- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:section];
        if ([[sectionData objectForKey:@"customHeaderView"] boolValue]) {;
            return [[sectionData objectForKey:@"customHeaderViewHeight"] floatValue];
        } else {;
            if (![[sectionData objectForKey:@"headerText"] isEqualToString:@""]) {;
                return 32;
            } else {;
                return 0;
            };
        };
    };
    
    return 0;
}

- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:section];
        if ([[sectionData objectForKey:@"customFooterView"] boolValue]) {;
            return [[sectionData objectForKey:@"customFooterViewHeight"] floatValue];
        } else {;
            if (![[sectionData objectForKey:@"footerText"] isEqualToString:@""]) {;
                return 32;
            } else {;
                return 0;
            };
        };
    };
    
    return 0;
}

- (NSInteger)tableView:(UITableView *)tableView indentationLevelForRowAtIndexPath:(NSIndexPath *)indexPath {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:indexPath.section];
        NSDictionary *cellData =  [[sectionData objectForKey:@"cells"] objectAtIndex:indexPath.row];
        return [[cellData objectForKey:@"indentationLevel"] integerValue];
    };
    
    return 0;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    if (tableView.tag == 1) {;
        NSDictionary *sectionData = [self.tableView1Data objectAtIndex:indexPath.section];
        NSDictionary *cellData =  [[sectionData objectForKey:@"cells"] objectAtIndex:indexPath.row];
        NSString *actionSelector = [cellData objectForKey:@"actionSelector"];
        if (actionSelector) {;
            UITableViewCell *cell = [tableView cellForRowAtIndexPath:indexPath];
            [self performSelector:NSSelectorFromString(actionSelector) withObject:cell];
        };
    };
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
}


// ----------------
// Navigation Bar
// ----------------

- (BOOL)navigationBar:(UINavigationBar *)navigationBar shouldPopItem:(UINavigationItem *)item {
    [self didTap_barButton1:nil forEvent:nil];
    return NO;
}

// ----------------
// Action
// ----------------

- (void)didTap_barButton1:(id)sender forEvent:(UIEvent *)event {
    [self.navigationController popViewControllerAnimated:YES];
}
- (void)didTap_tableViewCell2:(UIView *)cell {
    HistoryIntervalViewController *controller = [[HistoryIntervalViewController alloc] init];
    [self.navigationController pushViewController:controller animated:YES];
    
}

@end